### ISSUE TITLE
readdir: Eagerly determine file attributes

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#3]
Does performance benefit from eager getattr? Maybe we can at least return file stats that are easy to determine. E.g. instead of using `Files.list()` we might better be [using walkFileTree with zero depth](https://docs.oracle.com/javase/tutorial/essential/io/walk.html), which gives us basicfileattributes for each file.

> Some logging has shown me that after I return the list of file names, getattr is then called once for each file [...]
> -- [Source](https://stackoverflow.com/q/25938832/4014509)

**Comment by overheadhunter** [comment]
According to [this](https://www.cs.hmc.edu/~geoff/classes/hmc.cs135.201001/homework/fuse/fuse_doc.html#readdir-details), we don't need full file attributes during `readdir`:

> FUSE only looks at st_ino and the file-type bits of st_mode

**Comment by overheadhunter** [comment]
Probably we should leave `stat = NULL`, as there is no real benefit, if `getattr` gets called nonetheless. Checking the type of a node isn't free in Java, as the [DirectoryStream](https://docs.oracle.com/javase/8/docs/api/java/nio/file/DirectoryStream.html) doesn't contain such information.

Will go to bed now and decide tomorrow, if we should just close this.

**Comment by billziss-gh** [comment]
A couple of comments on this:

- FUSE 3+ supports "readdir plus". In this mode all (most?) `stat` fields are honored.

- WinFsp-FUSE supports its own "readdir plus" that is unfortunately incompatible with FUSE 3.x. (The reason is that WinFsp-FUSE is compatible with the FUSE 2.x series and the FUSE 3.x "readdir plus" extension requires a change in the `fuse_operations::readdir` signature.) This functionality is only enabled if the `FSP_FUSE_CAP_READDIR_PLUS` capability is enabled.

- I do not think jnr-fuse supports any of this right now though. I recommend that we ask the jnr-fuse project to add support for `FSP_FUSE_CAP_READDIR_PLUS` as it is an important optimization on Windows.

The addition of "readdir plus" makes a huge difference on Windows. The reason is that directory queries on Windows are always of the enumerate names+stat information variety, so the WinFsp-FUSE layer is forced to issue `readdir` followed by hundreds/thousands of `getattr` without this optimization.

**Comment by overheadhunter** [comment]
Closing this until there is a real benefit for FUSE (readdir plus mode?)...
