### ISSUE TITLE
File read/write operations

### ISSUE THREAD

**Issue by josephsmendoza** [cryptomator/fuse-nio-adapter#43]
I'm trying to implement something similar to Overlay FS, where I would need to save changes to files separately from the original files. It doesn't look like the Path API would allow that by itself. When a file is opened, I would need to read from the same file and write to a different one. Is there anything in this project that would allow me to intercept read/write requests?

**Comment by overheadhunter** [comment]
Well in order to implement a file system, you have to implement a file system. 😄 In case of Java, you'd probably want to implement `java.nio.file.spi.FileSystemProvider`. From your comment in the jnr-fuse repo, I assumed you had already done so.

Once you have implemented the `java.nio.file.*` API, if you receive a path object ([`Path p = yourFs.getPath("/")`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystem.html#getPath(java.lang.String,java.lang.String...))) and pass it to the [mount](https://github.com/cryptomator/fuse-nio-adapter/blob/1.2.3/src/main/java/org/cryptomator/frontend/fuse/mount/Mounter.java#L7) method, everything happening via fuse will pass through your [FileSystemProvider](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html), including read ([`newInputStream(...)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html#newInputStream(java.nio.file.Path,java.nio.file.OpenOption...))) and write ([`newOutputStream(...)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html#newOutputStream(java.nio.file.Path,java.nio.file.OpenOption...))).

**Comment by josephsmendoza** [comment]
I see, I was confused because I previously used a similar library which had `mount(FileSystem fs)`. Thanks for clarifying.
