### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by yiyang-dev** [cryptomator/fuse-nio-adapter#55]
jnr-fuse doesn't properly stat files when running on arm: https://github.com/SerCeMan/jnr-fuse/issues/14

This means that several things that rely on stat (e.g. basically anything that checks filesizes) breaks.

A possibility might be to replace the library with https://github.com/EtiennePerot/fuse-jna

**Comment by overheadhunter** [comment]
In comparison, JNA is slow. But we have plans to use [JEP 393](https://openjdk.java.net/jeps/393) and [JEP 389](https://openjdk.java.net/jeps/389) instead. Currently, we're still in a [proof of concept](https://github.com/skymatic/fuse-panama) phase, as you need to consider these new APIs experimental.

**Comment by yiyangc91** [comment]
Thanks!

Actually, I think the missing stat implementation turned out to be much, much worse than expected.

I copied everything out of my cryptomator directory into my home directory temporarily; and deleted my cryptomator directory. However because all the files stat 0 bytes, turns out cp will **literally copy zero bytes**, so I pretty much ended up deleting my entire vault...

Thankfully that was a test vault, but... yeah. Keep backups.
