### ISSUE TITLE
What is needed to be done?

### ISSUE THREAD

**Issue by pgolebiowski** [cryptomator/fuse-nio-adapter#9]
Basically, I am wondering what is needed to be done to consider this project an MVP ready for production use, i.e. integration with Cryptomator and release.

Understanding of your roadmap would make it easier for me to organize my own.

**Comment by tobihagemann** [comment]
1. Fix write bug when combining fuse-nio-adapter and [cryptofs](https://github.com/cryptomator/cryptofs)
2. Write mounter for fuse-nio-adapter (similar to [webdav-nio-adapter](https://github.com/cryptomator/webdav-nio-adapter))
3. Integrate into Cryptomator

This is the best-case scenario. We still don't know why it's not possible to write data in combination with cryptofs so debugging may take some time. It's quite possible that we'll have a beta build ready in January for public testing. But we won't make any promises since we may encounter unforeseen bugs/difficulties along the way.

**Comment by pgolebiowski** [comment]
Thank you very much for your response! It is really helpful ^^
